export const createOptions = {
  showLogicTab: false,
  isAutoSave: false,
  showTitlesInExpressions: true,
  showObjectTitles: true,
  previewDevice: "androidPhone",
  showDesignerTab: false,
  allowEditExpressionsInTextEditor: true,
  showDefaultLanguageInPreviewTab: false,
  previewOrientation: "portrait",
  addNewQuestionLast: true,
  readOnly: false,
  showJSONEditorTab: false,
  allowModifyPages: true,
  maxVisibleChoices: 8,
  showInvisibleElementsInPreviewTab: false,
  questionTypes: [
    "radiogroup",
    "checkbox",
    "dropdown",
    "text",
    "comment",
    "rating",
    "html",
    "file",
    "matrix",
    "multipletext",
    "panel",
    "signaturepad",
    "sortablelist",
    "flowpanel",
    "rating",
    "imagepicker",
    "ranking",
    "customcheckbox",
  ],
};